### ISSUE TITLE
Confirm the baseline AsciiDoc is correct

### ISSUE THREAD

**Issue by guw** [eclipse-architecture/eclipse-development-process#3]
#### Issue/Problem Description
* The board needs a diff of all the changes.

#### Proposal
* Confirm the current version of the AsciiDoc was converted correctly and can be used as a baseline.

Commit: 83eac6dd02a5dadf0c6edaf1668684b0691b075a

https://github.com/eclipse-architecture/eclipse-development-process/blob/83eac6dd02a5dadf0c6edaf1668684b0691b075a/eclipse_development_process.adoc

**Comment by guw** [comment]
@waynebeaton Have you had a chance to verify that this AsciiDoc baseline is correct?

**Comment by waynebeaton** [comment]
I've replaced what you have with a new upload in a pull request. I made a few changes, but it's fundamentally the same document. I'll do another pass before I declare success here.
