### ISSUE TITLE
Graphical view of release workflow(s)

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-architecture/eclipse-development-process#4]
#### Issue/Problem Description
* It's a bit hard from the doc to understand which workflow a release can use and what are the steps involved in term of approval. Understanding what a release involves requires moving in multiple places of the document and reading a lot of text, many of it being conditional, making it harder to sort out what's the path for a given case.

#### Proposal
* I suggest we show on the EDP a graphical view of the workflow(s) for releases. If there is actually no flow, but just a list of independent requirement, we should show the checklist for each review explicitly.
* The EDP release process could be an appendix, just like the IP Due Diligence poster which is extremely good for IP concerns (that I believe happen to be harder on paper, but easier to undersand thanks to the poster)

#### Proposal Benefits
* People understand release process better and can better pick the right kind of release they need according to their project constraints.

#### Challenges
* If it's an appendix, no immediate challenge.
* If we're likely to update the process often, then having an extra document could be an additional maintenance effort and a risk of out-of-date content.

**Comment by mickaelistria** [comment]
cc @waynebeaton IIRC, you authored the IP Due Diligence poster. Do you think a similar one would be doable and profitable for the release process(es)?

**Comment by waynebeaton** [comment]
How, specifically, would you improve the documentation?

https://www.eclipse.org/projects/handbook/#release-review

The IP Due Diligence Poster is a nightmare. Rethinking that has been on my
list for a while.

Wayne

**Comment by mickaelistria** [comment]
There is the case of release not requiring a review which doesn't appear on this graph. In this case, is there a step that replaces the release review/start end; or is the release ready immediately?

**Comment by waynebeaton** [comment]
The handbook is probably the right place for this. I've been trying to put more graphical flows in there. My intent is to make the handbook be the practical guide leaving the EDP as the foundational document. For one thing, changes to the EDP require board approval; tweaking the handbook can be done in a more ad hoc fashion.

i.e. something along these lines: https://www.eclipse.org/projects/handbook/#ip-prereq-cq

I'll see what I can come up with

**Comment by waynebeaton** [comment]
I've moved this to the handbook [issue tracker](https://gitlab.eclipse.org/eclipse/technology/dash/org.eclipse.dash.handbook/-/issues/170).

I did [attempt](https://www.eclipse.org/projects/handbook/#release-review) to address this based on the state of the process at the time, but the changes that we've made to the EDP and IP Process since this was issue created introduce some additional challenges.

In any case, we'll address them in the handbook.
